# Generated by Django 5.2.1 on 2025-06-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='des',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='performer',
            name='instrument',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='senior_home',
            name='contact',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='senior_home',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
