# Generated by Django 5.2.1 on 2025-06-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_performer_des_performer_instrument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='des',
            field=models.TextField(default='', max_length=2000, null=True),
        ),
    ]
