# Generated by Django 5.2.1 on 2025-06-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_performer_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(help_text='performer first name', max_length=100)),
                ('firstname', models.CharField(help_text='performer first name', max_length=100)),
                ('lastname', models.CharField(help_text='First Name', max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('inquiry', models.TextField(default='', max_length=2000)),
            ],
        ),
    ]
