# Generated by Django 5.2.1 on 2025-06-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_enquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performer',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='performer',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='lastname',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='first_name',
            field=models.CharField(default='', help_text='first name', max_length=100),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='last_name',
            field=models.CharField(default='', help_text='Last Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='about',
            field=models.CharField(help_text='performer or senior home', max_length=100),
        ),
    ]
