# Generated by Django 5.2.1 on 2025-07-01 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_firstname_performer_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='submitted',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 30, 17, 7, 41, 835259)),
        ),
    ]
